import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./providers/redux-provider";
import dynamic from "next/dynamic";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  fallback: ["Inter"],
});

export const metadata: Metadata = {
  title: "Chatto",
  description: "Generated by create next app",
};

const AppThemeProvider = dynamic(() => import("./providers/theme-provider"), {
  ssr: false,
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <link
          rel="icon"
          href="/assets/logos/logo.png"
          type="image/png"
          sizes="<generated>"
        />

        <body className={poppins.className}>
          <AppThemeProvider>{children}</AppThemeProvider>
        </body>
      </html>
    </ReduxProvider>
  );
}
